swagger: '2.0'
info:
  title: healthcheck
  x-ibm-name: healthcheck
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: "let vOutput = {};\r\nvOutput.ResponseDetails = {\"APIName\":\"\"};\r\nvOutput.ResponseDetails.APIName = context.get('api.name');\r\nvOutput.ResponseDetails.GatewayIP = context.get('session.localAddress');\r\nvOutput.ResponseDetails.RequestDate = context.get('request.date');\r\nvOutput.ResponseDetails.ClientAddress = context.get('session.clientAddress');\r\nvOutput.ResponseDetails.TransactionID = context.get('session.transactionID');\r\nvOutput.ResponseDetails.GlobalTransactionID = context.get('session.globalTransactionID');\r\nvOutput.ResponseDetails.StatusCode = context.get('message.status.code');\r\n\r\ncontext.message.body.write(vOutput);\r\ncontext.message.header.set('Content-Type', \"application/json\");"
    finally: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /healthcheck
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
schemes:
  - https
securityDefinitions: {}
security: []
